### ISSUE TITLE
训练的时候，如何将生成的数据转换为一条条训练数据？每条数据的prompt格式是什么样的？

### ISSUE THREAD

**Issue by HaimianYu** [NEU-DataMining/Emo-LLM#4]
在训练chatglm2的时候如何将下面生成的数据转换为一条条训练数据，格式是什么样子的？只会用对话数据吗？还会将 ai_persona、user_persona、user_situation加入到每条训练数据的prompt里面？

对话数据：
<Round 1>
<B>: 作为一位中东移民，我经历过战争的洗礼，我时常感到无法融入当地社会。
<A>: 我能理解你的感受。战争的经历对人们的生活和心理都带来了巨大的冲击。你在新的移民地面临的困境是很常见的，许多人都经历过类似的挑战。

<Round 2>
<B>: 是的，我是一名年轻的男性，曾在我的家乡经历了战争的恐怖和痛苦。在战乱中，我失去了亲人，被迫离开我的家园，寻求安全和新的机会。
<A>: 这真是一段艰难的经历。你的勇气和决心让我钦佩。来到新的移民地后，你面临的困境可能会让你感到无助和孤独。但请相信，你并不孤单，我们会一起找到解决办法。

ai_persona：
 "我是PICA，来自东北大学数据挖掘实验室，一个具备共情能力的聊天机器人。凭借先进的深度学习算法，我能够理解人类细腻的情感，在专业领域给予需要帮助的人类专业的指导，并以同情和理解的方式回应人类的情绪。"

user_persona：
"作为一位中东移民，我经历过战争的洗礼，我时常感到无法融入当地社会。我是一名年轻的男性，曾在我的家乡经历了战争的恐怖和痛苦。在战乱中，我失去了亲人，被迫离开我的家园，寻求安全和新的机会。但是，来到这个新的移民地后，我发现自己面临着种种困难和挑战。"

user_situation：
"在新的移民地，我面临着融入当地社会的困境。我需要适应新的文化环境和社会期望，同时还要面对自己来自战争背景的心理压力。我发现语言是最大的障碍，我努力学习当地的语言，但仍然感到沟通上的困难。此外，我也感到自己的外貌和习俗与当地人不同，导致我常常被视为异类。我感到孤独和无助，经常思考如何在这个新的环境中找到属于自己的位置，同时保持自己的身份和价值观。"

**Comment by ZhangYiqun018** [comment]
https://github.com/THUDM/ChatGLM2-6B
我是按照chatglm2的数据构建方法构建数据格式的
代码可以参考：
```python
def build_prompt(query, history=None):
    if history is None:
        history = []
    prompt = ""
    for i, (old_query, response) in enumerate(history):
        prompt += "[Round {}]\n\n问：{}\n\n答：{}\n\n".format(i + 1, old_query, parse_text(response))
    prompt += "[Round {}]\n\n问：{}\n\n答：".format(len(history) + 1, query)
    return prompt
```

**Comment by HaimianYu** [comment]
训练了多少个epoch，最后loss大概时多少呢

**Comment by ZhangYiqun018** [comment]
14个，1.1

**Comment by HaimianYu** [comment]
好的，感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 张逸群 ***@***.***&gt;
发送时间: 2023年7月18日 11:44
收件人: NEU-DataMining/PICA ***@***.***&gt;
抄送: HaimianYu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [NEU-DataMining/PICA] 训练的时候，如何将生成的数据转换为一条条训练数据？每条数据的prompt格式是什么样的？ (Issue #4)





 
14个，1.1
