### ISSUE TITLE
训练方式

### ISSUE THREAD

**Issue by cpl123456** [NEU-DataMining/Emo-LLM#8]
您好，请问一下PICA训练方式采用的是 全量参数微调 还是 参数高效微调？ 我测试了 您提供的模型，在角色多轮情感对话 效果挺不错的，但是 我 使用你 提供的 soulchat_result.json 作为数据集， 通过  https://github.com/hiyouga/ChatGLM-Efficient-Tuning 的 Sft 微调 没有达到 类似的 效果。可以提供 训练的参考示例吗？
还有一个问题，在原ChatGLM2-6B 角色对话 是没有下图效果好的，能否提供 少量的微调数据集？ 
![image](https://github.com/NEU-DataMining/PICA/assets/67935024/6ea9ac2c-68d5-4285-9258-d50b5d55fed2)

心里健康数据集我修改了格式：
    {
        "instruction": "我会尝试的。谢谢你的建议。",
        "input": "",
        "output": "不用客气，希望我的建议对你有所帮助。如果还有其他问题或者需要进一步指导，请随时告诉我。",
        "history": [
            [
                "联系的和帮助我的，到底谁算我的朋友？",
                "朋友这个词有很多不同的定义，每个人对朋友的理解也不尽相同。对于我来说，朋友是在你需要帮助时愿意伸出援手的人。所以，那些联系并帮助你的人可以算作你的朋友。"
            ],
            [
                "平时联系的是一些朋友，可是自己真有事时，想到的确实另一些人，虽然感觉自己跟平时联系的朋友说了，也会得到帮助，但是不想让他们知道，不知道为啥，是不是潜意识没有把他们当朋友？",
                "这种情况很常见。有时候我们可能更愿意向与我们没有太多关系或者更加熟悉我们内心世界的人倾诉。这并不代表你没有把平时联系的朋友当作真正的朋友。每个人都有自己独特的需求和情感依赖，在面对困难时选择与谁倾诉也是很正常的。"
            ],
            [
                "我明白了。但我还是想找到一个能够真正理解我的人，能够给我建议和支持的人。你有什么建议吗？",
                "当你想找到一个真正理解你的人时，可以尝试以下几个方法。首先，多与他人交流并表达自己的感受和需求，这样有助于别人更好地了解你。其次，寻找共同兴趣或者价值观相似的人，这样更容易建立深层次的连接。最后，也可以考虑寻求专业心理咨询师或者心理治疗师的帮助，他们具备专业知识和经验来帮助你理解自己并提供支持。"
            ],
            [
                "谢谢你的建议。我会尝试去寻找那个能够真正理解我的人，并向他们倾诉我的烦恼。",
                "很高兴能够为你提供帮助。记住，在寻找那个特殊的朋友过程中要保持开放和耐心。如果需要任何进一步的指导或者支持，请随时告诉我。"
            ],
            [
                "我会记住的。谢谢你一直陪伴着我倾听我的烦恼。",
                "不用客气，我很愿意陪伴并倾听你的烦恼。如果你还有其他问题或者需要进一步的帮助，请随时告诉我。"
            ],
            [
                "有时候我也会觉得自己很奇怪，明明有人愿意帮助我，但是我却不想让他们知道我的困境。",
                "这可能是因为你担心给他们增加负担或者觉得自己应该独自解决问题。但是记住，朋友之间应该相互支持和帮助。如果你需要帮助，不妨试着与他们分享你的困境，也许他们会给予你意想不到的支持和理解。"
            ]
        ]
    },

**Comment by ZhangYiqun018** [comment]
1. 您好，您使用的soulchat数据集应该是我用测试集用soulchat这个模型做的推理结果，这个数据用来做训练效果应该会比较差。
2. 我训练的方案就是chatglm2的p-tuning v2方法，您可以参考chatglm2的官方示例。如果确认训练方法没有问题，那您可以考虑数据集的格式，chatglm2是多轮对话模型，其组织数据的格式比较特殊，您也可以参考chatglm2的官方示例。
3. 基于psyqa数据集改造的数据由于开源协议问题不能提供，所以我的微调数据集在selfchat这个项目中开源了一部分，您可以自行查找，那个库目前有点乱，之后我会整理，若没有找到可以联系我。
